version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse-data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./app/logs:/app/logs
      - temp-storage:/tmp/pii_scanner
    ports:
      - "8000:8000"
    environment:
      - CLICKHOUSE_HOST=clickhouse-server
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-}
      - CLICKHOUSE_DATABASE=${CLICKHOUSE_DATABASE:-default}
      - MEMORY_LIMIT=1610612736  # 1.5GB in bytes
      - MAX_WORKERS=1
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1.5G
        reservations:
          memory: 1G
    ulimits:
      memlock:
        soft: 1610612736  # 1.5GB
        hard: 1610612736  # 1.5GB
    depends_on:
      - clickhouse-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 512M
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - prometheus

volumes:
  clickhouse-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  temp-storage:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=2g

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16