INSERT INTO region_mapping (code, continent, country) VALUES
('us-east-1', 'North America', 'USA'),
('us-east-2', 'North America', 'USA'),
('us-west-1', 'North America', 'USA'),
('us-west-2', 'North America', 'USA'),
('af-south-1', 'Africa', 'SOUTH AFRICA'),
('ap-east-1', 'Asia', 'CHINA'),
('ap-south-2', 'Asia', 'INDIA'),
('ap-southeast-3', 'Asia', 'INDONESIA'),
('ap-southeast-5', 'Asia', 'MALAYSIA'),
('ap-southeast-4', 'Australia', 'AUSTRALIA'),
('ap-south-1', 'Asia', 'INDIA'),
('ap-northeast-3', 'Asia', 'JAPAN'),
('ap-northeast-2', 'Asia', 'SOUTH KOREA'),
('ap-southeast-1', 'Asia', 'SINGAPORE'),
('ap-southeast-2', 'Australia', 'AUSTRALIA'),
('ap-southeast-7', 'Asia', 'THAILAND'),
('ap-northeast-1', 'Asia', 'JAPAN'),
('ca-central-1', 'North America', 'CANADA'),
('ca-west-1', 'North America', 'CANADA'),
('cn-north-1', 'Asia', 'CHINA'),
('cn-northwest-1', 'Asia', 'CHINA'),
('eu-central-1', 'Europe', 'GERMANY'),
('eu-west-1', 'Europe', 'IRELAND'),
('eu-west-2', 'Europe', 'UNITED KINGDOM'),
('eu-south-1', 'Europe', 'ITALY'),
('eu-west-3', 'Europe', 'FRANCE'),
('eu-south-2', 'Europe', 'SPAIN'),
('eu-north-1', 'Europe', 'SWEDEN'),
('eu-central-2', 'Europe', 'SWITZERLAND'),
('il-central-1', 'Asia', 'ISRAEL'),
('mx-central-1', 'North America', 'MEXICO'),
('me-south-1', 'Middle East', 'BAHRAIN'),
('me-central-1', 'Middle East', 'UAE'),
('sa-east-1', 'South America', 'BRAZIL');