INSERT INTO region_mapping (code, continent, country) VALUES
('us-east-1', 'North America', 'USA'),
('us-east-2', 'North America', 'USA'),
('us-west-1', 'North America', 'USA'),
('us-west-2', 'North America', 'USA'),
('af-south-1', 'Africa', 'South Africa'),
('ap-east-1', 'Asia', 'China'),
('ap-south-2', 'Asia', 'India'),
('ap-southeast-3', 'Asia', 'Indonesia'),
('ap-southeast-5', 'Asia', 'Malaysia'),
('ap-southeast-4', 'Australia', 'Australia'),
('ap-south-1', 'Asia', 'India'),
('ap-northeast-3', 'Asia', 'Japan'),
('ap-northeast-2', 'Asia', 'South Korea'),
('ap-southeast-1', 'Asia', 'Singapore'),
('ap-southeast-2', 'Australia', 'Australia'),
('ap-southeast-7', 'Asia', 'Thailand'),
('ap-northeast-1', 'Asia', 'Japan'),
('ca-central-1', 'North America', 'Canada'),
('ca-west-1', 'North America', 'Canada'),
('cn-north-1', 'Asia', 'China'),
('cn-northwest-1', 'Asia', 'China'),
('eu-central-1', 'Europe', 'Germany'),
('eu-west-1', 'Europe', 'Ireland'),
('eu-west-2', 'Europe', 'United Kingdom'),
('eu-south-1', 'Europe', 'Italy'),
('eu-west-3', 'Europe', 'France'),
('eu-south-2', 'Europe', 'Spain'),
('eu-north-1', 'Europe', 'Sweden'),
('eu-central-2', 'Europe', 'Switzerland'),
('il-central-1', 'Asia', 'Israel'),
('mx-central-1', 'North America', 'Mexico'),
('me-south-1', 'Middle East', 'Bahrain'),
('me-central-1', 'Middle East', 'UAE'),
('sa-east-1', 'South America', 'Brazil');
